language: clojure
lein: lein2
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - $TEST_CMD
env:
  - TEST_CMD="lein midje"
  - TEST_CMD="lein with-profile +1.6 midje"
  - TEST_CMD="lein with-profile +1.7 midje"
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  include:
    - env: TEST_CMD="lein with-profile +1.7 coverage --coveralls"
      jdk: oraclejdk8
    - env: TEST_CMD="lein with-profile +1.7 eastwood"
      jdk: oraclejdk8
